# Generated by Django 3.0.6 on 2020-06-13 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='photo_web',
            field=models.ImageField(null=True, upload_to='webs/'),
        ),
    ]
